In [1]:
# Import standard libraries
import numpy as np
import math
import scipy.stats as stats
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import sqlite3
from collections import Counter, defaultdict

sns.set_style('whitegrid')

%config InlineBackend.figure_format = 'retina'
%matplotlib inline


# Import sklearn packages
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, classification_report
from sklearn.metrics import mean_squared_error

# Import other packages
from datetime import datetime
import pickle
from ast import literal_eval

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

### 5) Content-based filtering recommender system

In [2]:
# load rest_reviews_nv pickle file
with open("rest_reviews_nv.pkl", "rb") as f:
    rest_reviews_nv = pickle.load(f)

In [5]:
rest_reviews_nv.head()

,review_id,business_id,user_id,user_stars,text,date,name,rest_avg_stars,review_count,categories,...,noise_lvl,credit_cards,wifi,alcohol,open_24hrs,serves_breakfast,serves_lunch,serves_dinner,is_chain,unique_store_id
1,lvEYRVCVtzkWs8HhO9NhCw,I4Nr-MVc26qWr08-S3Q1ow,7Inj11uN96hJUXAxrG2Saw,5.0,My wife ate here and I had pizza from another ...,2016-03-07,Greenberg's Deli,4.0,333,"Delis, Sandwiches, Pizza",...,average,1,1,1,0,1,1,1,0,Greenberg's Deli
5,Fid16Utz654-3h2Wb96ttA,I4Nr-MVc26qWr08-S3Q1ow,XKo5IT6o-WslzHPT69PRSQ,3.0,I had lunch for the first time at this locatio...,2013-02-22,Greenberg's Deli,4.0,333,"Delis, Sandwiches, Pizza",...,average,1,1,1,0,1,1,1,0,Greenberg's Deli
9,h-S9hbHrkV8rFegFqpdf_Q,I4Nr-MVc26qWr08-S3Q1ow,nCsfMqpfOGcTFKEZ3C1_Gg,4.0,this place makes a great pastrami or Reuben sa...,2013-12-08,Greenberg's Deli,4.0,333,"Delis, Sandwiches, Pizza",...,average,1,1,1,0,1,1,1,0,Greenberg's Deli
17,W1mPDutV0JZuaLBWgAWxTA,I4Nr-MVc26qWr08-S3Q1ow,51UaY_JKrEOzA1CeEbuDNg,4.0,"The New York, New York does the ""Food Court"" i...",2007-12-12,Greenberg's Deli,4.0,333,"Delis, Sandwiches, Pizza",...,average,1,1,1,0,1,1,1,0,Greenberg's Deli
24,XqPkNCAVDBbEawwfZVzPGw,I4Nr-MVc26qWr08-S3Q1ow,nW4POvJR2MqjU90mnNPqvA,4.0,Alright I have to admit..I'm still dreaming of...,2010-05-17,Greenberg's Deli,4.0,333,"Delis, Sandwiches, Pizza",...,average,1,1,1,0,1,1,1,0,Greenberg's Deli

In [7]:
# number of unique restaurants

rest_reviews_nv['business_id'].value_counts()

4JNXUYY8wbaaDmk3BPzlWw    1156
K7lWdNUhCbcnEvI0NhGewg    1138
RESDUcs7fIiihp38-d6_6g    1123
DkYS3arLOhA8si5uUEmHOw    1110
iCQpiavjjPzJ5_3gPD5Ebg     979
UPIYuRaZvknINOd1w8kqRQ     816
P7pxQFqr7yBKMMI2J51udw     764
KskYqH1Bi7Z_61pH6Om8pg     737
rcaPajgKOJC2vo_l3xa42A     731
f4x1YBxkLrZg652xt2KR5g     659
ujHiaprwCQ5ewziu0Vi9rw     566
NvKNe9DnQavC9GstglcBJQ     542
awI4hHMfa7H0Xf0-ChU5hg     531
XZbuPXdyA0ZtTu3AzqtQhg     520
JyxHvtj-syke7m9rbza7mA     511
XXW_OFaYQkkGOGniujZFHg     499
RwMLuOkImBIqqYj4SSKSPg     496
l_GV0hgEoTUf70uJVT0_hg     483
3BCsAgo_1i4xMuTyLKMLRQ     469
gx2yPrOJSwF1ApJYdGBWIw     466
faPVqws-x-5k2CQKDNtHxw     453
uW6UHfONAmm8QttPkbMewQ     447
zdE82PiD6wquvjYLyhOJNA     436
IMLrj2klosTFvPRLv56cng     435
A5Rkh7UymKm0_Rxm9K2PJw     429
UNI1agsPX2k3eJSJVB91nw     427
sNVGdeOPeitJ3OWUQBINzQ     418
5LNZ67Yw9RD6nf4_UhXOjw     407
2iTsRqUsPGRH1li1WVRvKQ     404
vl2IZrNJEA8npSjqXbdwxw     388
                          ...
mwERWE8IqgcmPHg3cpCfNA      11
GQCmcU4aD6GEq7Eo7pKqUg      11
GtHu9uGXpn7Jg_Z7vFKZKw      11
PpD_gfjcw5nsjRmFeAR3_Q      11
gg0zeYKlmvk_rScipyOyKw      11
cw8oFCL0BxCQCwwAr8DOOw      11
q4i-GbjeSp6ucBDXGE9DqA      11
GjbF1ZEbIpC2KqUbZ7KQWQ      11
ViF5Kd7pBF1JJhlvEy1kpA      11
RrKvj24rmHndsO8A19lTyQ      11
gNhxs9nPUSkVBSSIRQOgaA      11
94GNGMxmruuqRLRhLqllWw      11
TN89zi12H1TXgFoELFCE4w      11
idPAwtnvruaB7YivrvFbzA      11
zp-K5s3pGTWuuaVBWo6WZA      11
opwxvFwYTppE0JgfM4FBlw      11
zbZX8D5sd9XZa6l6fQDN1A      11
LwXo16VrGPhhOWc_Wj7ifw      11
AT1bODcrWTKTRNZKRxO-cA      11
7zMwR4FkvTbSGY0vRT5Ljg      11
eY98EH_PHGnJVaJ7t2UpoQ      11
nl2nsBi9U3sW1R34nF0s0Q      11
mZI_wVrLOjz4M-QIC9n-jA      11
GTcnXw53TmOkpzFPmuRI6w      11
sIr0Wp13Z_MqwgcNvF-5ew      11
l4E8kiB13FWV1p_rGYJLig      11
4VXIS8vpNzEysXZVN5xGDA      11
g6w4kX7tvCqGKAxr07aBQA      11
3dC3opMY67zrquz_yYc-tw      11
W_qjGgy4LsEQnKKjIscDNg      11
Name: business_id, Length: 1713, dtype: int64

In [ ]:
# Merge all the review text for each restaurant

concat_text_col = df.groupby('business_id')['text'].apply(lambda x: x.sum())
concat_text_col.shape

In [ ]:
# Concatenate all the columns for

In [123]:
# Extract restaurants that have been filtered and reviwed 

businesses_reviewed = rest_reviews_nv.drop(['review_id', 'user_id', 'user_stars', 'text', 'date'], axis = 1).drop_duplicates()
businesses_reviewed.shape

(1713, 26)

In [50]:
businesses_reviewed = pd.read_csv('businesses_reviewed.csv')

In [51]:
businesses_reviewed.shape

(1615, 25)

In [4]:
businesses_reviewed.head()

,business_id,name,rest_avg_stars,review_count,categories,postal_code,latitude,longitude,pricerange,is_open,...,noise_lvl,credit_cards,wifi,alcohol,open_24hrs,serves_breakfast,serves_lunch,serves_dinner,is_chain,unique_store_id
0,I4Nr-MVc26qWr08-S3Q1ow,Greenberg's Deli,4.0,333,"Delis, Sandwiches, Pizza",89136.0,36.102379,-115.174547,2,1,...,average,1,1,1,0,1,1,1,0,Greenberg's Deli
1,d_L-rfS1vT3JMzgCUGtiow,Border Grill,4.0,1623,"Breakfast & Brunch, Tapas/Small Plates, Mexican",89119.0,36.090067,-115.176973,2,1,...,average,1,1,1,0,1,1,1,1,Border Grill (Outlet 1 - 89119)
2,Sfc8Haz2Yri8Mo1L0E0TsA,Chicken Bonz,3.0,52,"Chicken Wings, Burgers",89118.0,36.071196,-115.207463,2,0,...,average,1,1,1,0,1,1,1,1,Chicken Bonz (Outlet 1 - 89118)
3,Gyrez6K8f1AyR7dzW9fvAw,Casanova,4.0,495,"Tapas Bars, Mediterranean, Italian",89109.0,36.121579,-115.168664,2,1,...,average,1,1,1,0,1,1,1,0,Casanova
4,dm6sO_Y8JdKTE1ZM955yug,Chada Thai & Wine,4.5,464,"Wine Bars, Bars, Thai, Nightlife",89146.0,36.127375,-115.224171,2,0,...,average,1,0,1,0,0,0,1,0,Chada Thai & Wine

In [5]:
businesses_reviewed.columns

Index(['business_id', 'name', 'rest_avg_stars', 'review_count', 'categories',
       'postal_code', 'latitude', 'longitude', 'pricerange', 'is_open',
       'outdoor_seat', 'rest_good_for_groups', 'good_kids', 'rest_reserve',
       'rest_deliver', 'noise_lvl', 'credit_cards', 'wifi', 'alcohol',
       'open_24hrs', 'serves_breakfast', 'serves_lunch', 'serves_dinner',
       'is_chain', 'unique_store_id'],
      dtype='object')

In [24]:
businesses_reviewed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 25 columns):
business_id             1615 non-null object
name                    1615 non-null object
rest_avg_stars          1615 non-null float64
review_count            1615 non-null int64
categories              1615 non-null object
postal_code             1612 non-null float64
latitude                1615 non-null float64
longitude               1615 non-null float64
pricerange              1615 non-null int64
is_open                 1615 non-null int64
outdoor_seat            1615 non-null int64
rest_good_for_groups    1615 non-null int64
good_kids               1615 non-null int64
rest_reserve            1615 non-null int64
rest_deliver            1615 non-null int64
noise_lvl               1615 non-null object
credit_cards            1615 non-null int64
wifi                    1615 non-null int64
alcohol                 1615 non-null int64
open_24hrs              1615 non-null int64
serves_breakfast        1615 non-null int64
serves_lunch            1615 non-null int64
serves_dinner           1615 non-null int64
is_chain                1615 non-null int64
unique_store_id         1615 non-null object
dtypes: float64(4), int64(16), object(5)
memory usage: 315.5+ KB

In [22]:
businesses_reviewed['categories'].head()[0][1]

' Sandwiches'

In [60]:
# Prepare data for modelling

# Select numerical columns for modelling - include unique store id for identification
num_col = ['unique_store_id', 'rest_avg_stars', 'review_count', 'pricerange', 'is_open', 'outdoor_seat', 
           'rest_good_for_groups', 'good_kids', 'rest_reserve', 'rest_deliver', 'credit_cards', 'wifi', 'alcohol',
          'open_24hrs', 'serves_breakfast', 'serves_dinner', 'is_chain']

start_col = 'rest_avg_stars'
end_col = 'is_chain'

num_matrix = businesses_reviewed[num_col]
num_matrix = num_matrix.reset_index() # This produces a separate index
num_matrix.rename({'index': 'restaurant'}, axis = 1, inplace = True)

# Create a non_num_matrix for 'categories' column to be count vectorized and apply get_dummies to 'noise_lvl' attribute
cvec = CountVectorizer(stop_words = 'english')
non_num_matrix = pd.DataFrame(cvec.fit_transform(businesses_reviewed['categories']).toarray(), columns = cvec.get_feature_names())
noise_matrix = pd.get_dummies(businesses_reviewed['noise_lvl'], prefix = 'noiselvl')
non_num_matrix = pd.concat([non_num_matrix, noise_matrix], axis = 1)

In [65]:
res_matrix.head()

,restaurant,unique_store_id,rest_avg_stars,review_count,pricerange,is_open,outdoor_seat,rest_good_for_groups,good_kids,rest_reserve,...,weight,wine,wings,wraps,yogurt,zoos,noiselvl_average,noiselvl_loud,noiselvl_quiet,noiselvl_very_loud
0,0,Greenberg's Deli,4.0,333,2,1,0,1,1,0,...,0,0,0,0,0,0,1,0,0,0
1,1,Border Grill (Outlet 1 - 89119),4.0,1623,2,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,0
2,2,Chicken Bonz (Outlet 1 - 89118),3.0,52,2,0,0,1,1,0,...,0,0,1,0,0,0,1,0,0,0
3,3,Casanova,4.0,495,2,1,0,1,1,1,...,0,0,0,0,0,0,1,0,0,0
4,4,Chada Thai & Wine,4.5,464,2,0,0,1,0,1,...,0,1,0,0,0,0,1,0,0,0

In [98]:
list = []

list.extend(res_matrix[res_matrix['unique_store_id'] == 'Chada Thai & Wine'].index)

In [99]:
list

[4]

In [63]:
# Concat both numeric and non-numeric matrices

res_matrix = pd.concat([num_matrix, non_num_matrix], axis = 1)

In [159]:
def similar_restaurants(res_list, start_col = 'rest_avg_stars', end_col = 'noiselvl_very_loud', 
                        num_similar_res = 10, num_recommended_res = 3):
    unique_res_list = []
    for res in res_list:
        # Get index of restaurant list 
        unique_res_list.extend(res_matrix[res_matrix['unique_store_id'] == res].index)
    # Get similar customers' restaurants index preferences    
    unique_res_list = np.unique(unique_res_list)

    # Generate average scores of the restarant list
    df_ref = pd.DataFrame(columns = res_matrix.loc[:, start_col:].columns)
    # provide list of indices from the list of restaurants and all cols
    df_ref.loc[0, :] = res_matrix.loc[unique_res_list, start_col:].mean()
    
    # Generate restaurant similarity between res_list and the rest of the other restaurants
    res_similarity = cosine_similarity(df_ref, res_matrix.loc[:, start_col:])
    print(res_similarity)
    
    # Find top n most similar res to avg of restaurant list by cosine similarity score
    unique_res_list_id = np.argsort(res_similarity)[0][-(num_similar_res + 1):-1]
    print(unique_res_list_id)
    
    # Sort by number of stars
    top_n_recommended_res = res_matrix.loc[unique_res_list_id, 'rest_avg_stars'].sort_values(ascending = False)[: num_recommended_res].index.tolist()
    
    
    print('Recommended top {} restaurant id are {}:'.format(num_recommended_res, top_n_recommended_res))
    
    top_n_res_name = []
    for ind in top_n_recommended_res:
          top_n_res_name.append(res_matrix.loc[ind, 'unique_store_id'])
    print('Recommended top {} restaurant names are {}'.format(num_recommended_res, str(top_n_res_name)))
          
    return top_n_recommended_res

In [160]:
similar_restaurants(["Greenberg's Deli", 'Casanova', 'Chada Thai & Wine'])

[[0.99997781 0.99995231 0.99637142 ... 0.99713672 0.99075342 0.99689316]]
[1101 1187  159  557  887 1457  384 1227 1239  424]
Recommended top 3 restaurant id are [1457, 557, 159]:
Recommended top 3 restaurant names are ['El Sombrero Mexican Bistro', 'MerÃ¡ki Greek Grill', 'Bocho Sushi']

[1457, 557, 159]

In [ ]:
# from popular restaurants generated by similar users

In [113]:
unique_res_list = []
for res in ["Greenberg's Deli", 'Casanova', 'Chada Thai & Wine']:
    # Get index of restaurant list 
    unique_res_list.extend(res_matrix[res_matrix['unique_store_id'] == res].index)
# Get similar customers' restaurants index preferences    
unique_res_list = np.unique(unique_res_list)
unique_res_list

array([0, 3, 4])

In [114]:
# Prepare empty dataframe to generate average scores of the restarant list
df_ref = pd.DataFrame(columns = res_matrix.loc[:, start_col:].columns)

# provide list of indices from the list of restaurants and all cols
df_ref.loc[0, :] = res_matrix.loc[unique_res_list, start_col:].mean()

In [115]:
df_ref

,rest_avg_stars,review_count,pricerange,is_open,outdoor_seat,rest_good_for_groups,good_kids,rest_reserve,rest_deliver,credit_cards,...,weight,wine,wings,wraps,yogurt,zoos,noiselvl_average,noiselvl_loud,noiselvl_quiet,noiselvl_very_loud
0,4.16667,430.667,2,0.666667,0,1,0.666667,0.666667,0,1,...,0,0.333333,0,0,0,0,1,0,0,0

In [66]:
df_ref = pd.DataFrame(columns = res_matrix.loc[:, start_col:].columns)
# provide list of indices from the list of restaurants and all cols
df_ref.loc[0, :] = res_matrix.loc[top_n_similar_preference_id, start_col:].mean()

In [125]:
# Generate restaurant similarity between res_list and the rest of the other restaurants
res_similarity = cosine_similarity(df_ref, res_matrix.loc[:, start_col:])
print(res_similarity[0][1239])

0.9999904896691414

In [133]:
# Find top n most similar res to avg of restaurant list by cosine similarity score
unique_res_list_id = np.argsort(res_similarity)[0][-(10 + 1):-1]
print(unique_res_list_id)

[1101 1187  159  557  887 1457  384 1227 1239  424]

In [157]:
top_n_recommended_res = res_matrix.loc[unique_res_list_id, 'rest_avg_stars'].sort_values(ascending = False)[: 3].index.tolist()

In [158]:
top_n_recommended_res

[1457, 557, 159]

In [139]:
top_n_res_name = []
for ind in top_n_recommended_res:
      top_n_res_name.append(res_matrix.loc[ind, 'unique_store_id'])

In [140]:
top_n_res_name

['El Sombrero Mexican Bistro', 'MerÃ¡ki Greek Grill', 'Bocho Sushi']

In [143]:
res_matrix.loc[384,:]

restaurant                          384
unique_store_id         A.Y.C.E. Buffet
rest_avg_stars                        4
review_count                        456
pricerange                            2
is_open                               1
outdoor_seat                          0
rest_good_for_groups                  1
good_kids                             1
rest_reserve                          0
rest_deliver                          0
credit_cards                          1
wifi                                  1
alcohol                               1
open_24hrs                            0
serves_breakfast                      1
serves_dinner                         1
is_chain                              0
acai                                  0
active                                0
adult                                 0
african                               0
american                              0
antiques                              0
arcades                               0
argentine                             0
art                                   0
arts                                  0
asian                                 0
automotive                            0
                             ...
thai                                  0
theater                               0
themed                                0
tours                                 0
traditional                           0
travel                                0
trucks                                0
tuscan                                0
ukrainian                             0
vegan                                 0
vegetarian                            0
veggies                               0
vendors                               0
venezuelan                            0
venues                                0
video                                 0
videos                                0
vietnamese                            0
waffles                               0
wedding                               0
weight                                0
wine                                  0
wings                                 0
wraps                                 0
yogurt                                0
zoos                                  0
noiselvl_average                      1
noiselvl_loud                         0
noiselvl_quiet                        0
noiselvl_very_loud                    0
Name: 384, Length: 300, dtype: object

In [132]:
# Sort by number of stars
top_n_recommended_res = list(res_matrix.loc[unique_res_list_id, 'rest_avg_stars'].sort_values(ascending = False)[: 3].index)

TypeError: 'list' object is not callable

In [128]:
res_matrix.loc[:, start_col:]

,rest_avg_stars,review_count,pricerange,is_open,outdoor_seat,rest_good_for_groups,good_kids,rest_reserve,rest_deliver,credit_cards,...,weight,wine,wings,wraps,yogurt,zoos,noiselvl_average,noiselvl_loud,noiselvl_quiet,noiselvl_very_loud
0,4.0,333,2,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1,4.0,1623,2,1,1,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
2,3.0,52,2,0,0,1,1,0,0,1,...,0,0,1,0,0,0,1,0,0,0
3,4.0,495,2,1,0,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
4,4.5,464,2,0,0,1,0,1,0,1,...,0,1,0,0,0,0,1,0,0,0
5,4.0,1615,2,1,0,1,1,1,0,1,...,0,1,0,0,0,0,1,0,0,0
6,4.0,1517,2,1,1,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
7,3.5,4227,3,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
8,3.0,1367,2,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
9,4.0,265,2,1,0,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,0
10,4.0,500,2,1,0,1,1,1,0,1,...,0,1,0,0,0,0,1,0,0,0
11,3.5,133,2,0,0,1,1,1,1,1,...,0,0,0,0,0,0,0,0,1,0
12,3.5,231,2,1,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
13,4.0,86,2,1,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
14,4.0,287,3,0,0,1,0,1,0,1,...,0,1,0,0,0,0,1,0,0,0
15,4.0,838,4,0,0,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
16,4.0,300,3,1,0,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
17,3.5,3222,2,1,1,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
18,4.0,3260,2,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
19,4.0,385,1,1,0,1,1,0,1,1,...,0,0,0,0,0,0,0,0,1,0
20,4.0,306,2,0,1,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
21,3.5,786,3,0,1,1,0,1,0,1,...,0,0,0,0,0,1,0,0,0,1
22,4.5,598,2,1,0,1,0,1,0,1,...,0,1,0,0,0,0,1,0,0,0
23,4.0,166,1,0,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
24,4.5,669,2,1,0,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
25,3.5,562,2,1,0,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
26,4.5,3576,2,1,0,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
27,3.5,292,2,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
28,4.5,1624,2,1,1,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
29,3.5,256,3,1,0,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1585,4.0,77,1,0,0,1,1,0,1,1,...,0,0,0,0,0,0,0,0,1,0
1586,3.0,120,2,1,0,1,0,0,1,1,...,0,0,0,1,0,0,1,0,0,0
1587,4.0,126,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1588,4.5,52,1,1,1,1,1,0,1,1,...,0,0,0,1,0,0,0,0,1,0
1589,4.5,102,4,1,0,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
1590,4.0,90,2,1,0,1,1,1,0,1,...,0,0,1,0,0,0,1,0,0,0
1591,4.0,87,2,0,0,1,1,0,1,1,...,0,0,0,0,0,0,1,0,0,0
1592,4.5,80,1,0,0,1,1,0,1,1,...,0,0,1,0,0,0,1,0,0,0
1593,4.5,113,2,1,0,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
1594,4.0,122,2,1,0,1,1,1,0,1,...,0,0,0,0,0,0,0,0,1,0
1595,4.5,106,3,1,0,1,0,1,0,1,...,0,1,0,0,0,0,1,0,0,0
1596,3.5,119,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1597,2.0,101,1,1,1,1,1,0,0,1,...,0,0,0,0,1,0,0,0,1,0
1598,3.0,76,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1599,3.5,130,2,1,1,1,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
1600,3.5,97,2,0,1,1,1,0,1,1,...,0,0,0,0,0,0,1,0,0,0
1601,2.5,109,1,1,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1602,3.5,122,2,1,0,1,1,1,0,1,...,0,0,0,0,0,0,0,0,1,0
1603,3.5,109,2,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1604,1.5,53,1,1,0,1,1,0,0,1,...,0,0,1,0,0,0,1,0,0,0
1605,3.5,52,1,1,1,1,1,0,1,1,...,0,0,1,0,0,0,0,0,1,0
1606,4.5,73,1,0,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1607,4.0,130,2,0,0,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
1608,2.5,61,2,0,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1609,4.5,74,2,0,0,1,1,1,0,1,...,0,0,0,0,0,0,1,0,0,0
1610,3.0,73,1,1,1,1,1,0,1,1,...,0,0,0,0,0,0,1,0,0,0
1611,3.5,104,2,0,1,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0
1612,3.5,57,1,0,1,1,1,1,1,1,...,0,0,0,0,0,0,1,0,0,0
1613,3.5,32,2,0,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1614,2.5,47,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,1,0,0,0

In [121]:
unique_res_list_id = np.argsort(res_similarity)[0][-(10 + 1):-1]
print(unique_res_list_id)

[1101 1187  159  557  887 1457  384 1227 1239  424]

In [202]:
similar_restaurants(["Greenberg's Deli", 'Casanova', 'Chada Thai & Wine'])

[[0.99997781 0.99995231 0.99637142 ... 0.99713672 0.99075342 0.99689316]]
[1101 1187  159  557  887 1457  384 1227 1239  424]
Recommended top 3 restaurant id are [1457, 557, 159]:
Recommended top 3 restaurant names are ['El Sombrero Mexican Bistro', 'MerÃ¡ki Greek Grill', 'Bocho Sushi']

[1457, 557, 159]