In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import roc_curve, auc, confusion_matrix, classification_report, accuracy_score

from datetime import datetime
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import xgboost as xgb

Join both review and metadata datasets from zip file

In [2]:
reviewContent = pd.read_csv("ReviewContent", names = ['user_id', 'prod_id', 'date', 'review'], sep = '\t', parse_dates = ['date'])
metadata = pd.read_csv("metadata",names=["user_id", "prod_id", "rating", "label", "date"], sep = '\t', parse_dates = ['date'])



reviews = pd.merge(reviewContent, metadata, how = 'left', 
                    left_on = ['user_id', 'prod_id', 'date'], right_on = ['user_id', 'prod_id', 'date'])

In [3]:
reviews.head()

,user_id,prod_id,date,review,rating,label
0,5044,0,2014-11-16,"Drinks were bad, the hot chocolate was watered...",1.0,-1
1,5045,0,2014-09-08,This was the worst experience I've ever had a ...,1.0,-1
2,5046,0,2013-10-06,This is located on the site of the old Spruce ...,3.0,-1
3,5047,0,2014-11-30,I enjoyed coffee and breakfast twice at Toast ...,5.0,-1
4,5048,0,2014-08-28,I love Toast! The food choices are fantastic -...,5.0,-1

In [4]:
reviews[reviews['user_id'] == 923]

Empty DataFrame
Columns: [user_id, prod_id, date, review, rating, label]
Index: []

In [5]:
# Convert classification of fake reviews from '-1' to '0'

reviews['label'] = reviews['label'].apply(lambda x: 0 if x == -1 else x)

In [6]:
reviews['label'].value_counts()

1    528019
0     80439
Name: label, dtype: int64

## Model 1: Experiment with using only review text to predict rating (w/o feature engineering)

In [7]:
model1 = reviews[['review', 'label']]

In [8]:
model1.head()

                                              review  label
0  Drinks were bad, the hot chocolate was watered...      0
1  This was the worst experience I've ever had a ...      0
2  This is located on the site of the old Spruce ...      0
3  I enjoyed coffee and breakfast twice at Toast ...      0
4  I love Toast! The food choices are fantastic -...      0

In [9]:
# Calculate baseline

baseline = model1['label'].mean()
baseline

0.8677985990816128

If any review is drawn by chance, there is a 86.8% probability that it is a real review.

try no class imbalance first

**Model 1.1: Using SVM**

In [11]:
X = reviews['review']
y = reviews['label']

In [12]:
X.head()

0    Drinks were bad, the hot chocolate was watered...
1    This was the worst experience I've ever had a ...
2    This is located on the site of the old Spruce ...
3    I enjoyed coffee and breakfast twice at Toast ...
4    I love Toast! The food choices are fantastic -...
Name: review, dtype: object

In [ ]:
# preprocessing of text data (ngram = 2)
from datetime import datetime
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (2,2), min_df = 3, stop_words = 'english')
Xs = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs.shape)

In [47]:
# Test using svc_classifier

from sklearn.svm import SVC, LinearSVC

svc_classifier = SVC()
score = cross_val_score(svc_classifier, Xs, y, cv = 2, n_jobs = -1)

print(datetime.now() - t1)
print(score)

0:11:45.842323
[0.80437498 0.80851532]

In [12]:
# preprocessing of text data (ngram = 1)



t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 1), min_df = 3, stop_words = 'english')
Xs1 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs1.shape)

0:02:00.203980
(608458, 66410)

In [ ]:
# Test using svc_classifier

from sklearn.svm import SVC, LinearSVC

svc_classifier = SVC()
score = cross_val_score(svc_classifier, Xs1, y, cv = 2, n_jobs = -1)

print(datetime.now() - t1)
print(score)

In [50]:
# preprocessing of text data (ngram = 1, 2)

t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 2), min_df = 3, stop_words = 'english')
Xs1 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs.shape)

0:02:56.721422
(608458, 1446832)

In [51]:
# Test using svc_classifier

svc_classifier = LinearSVC()
score = cross_val_score(svc_classifier, Xs1, y, cv = 2, n_jobs = -1)

print(datetime.now() - t1)
print(score)

0:06:14.809903
[0.80677777 0.81179576]

In [52]:
# preprocessing of text data (ngram = 1, 2, remove stop_words)

t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 2), min_df = 3)
Xs1 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs1.shape)

0:04:00.054039
(608458, 1446832)

In [54]:
# Test using svc_classifier

svc_classifier = LinearSVC()
score = cross_val_score(svc_classifier, Xs1, y, cv = 2, n_jobs = -1)

print(Xs1.shape)
print(datetime.now() - t1)
print(score)

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

In [42]:
cvec.get_feature_names()

['00 00',
 '00 10',
 '00 11',
 '00 12',
 '00 15',
 '00 20',
 '00 24',
 '00 30',
 '00 30pm',
 '00 50',
 '00 99',
 '00 about',
 '00 add',
 '00 added',
 '00 after',
 '00 again',
 '00 all',
 '00 almost',
 '00 also',
 '00 although',
 '00 am',
 '00 an',
 '00 and',
 '00 another',
 '00 anyway',
 '00 appetizer',
 '00 appetizers',
 '00 are',
 '00 as',
 '00 asked',
 '00 at',
 '00 awesome',
 '00 back',
 '00 be',
 '00 because',
 '00 beer',
 '00 beers',
 '00 before',
 '00 believe',
 '00 best',
 '00 between',
 '00 bill',
 '00 both',
 '00 bottle',
 '00 bottles',
 '00 bowl',
 '00 brunch',
 '00 bucks',
 '00 burger',
 '00 but',
 '00 by',
 '00 calamari',
 '00 came',
 '00 can',
 '00 card',
 '00 change',
 '00 charge',
 '00 cheap',
 '00 cheaper',
 '00 check',
 '00 chicken',
 '00 chose',
 '00 clock',
 '00 cocktails',
 '00 comes',
 '00 corkage',
 '00 could',
 '00 couple',
 '00 coupon',
 '00 crazy',
 '00 credit',
 '00 cup',
 '00 deal',
 '00 decided',
 '00 definitely',
 '00 delivery',
 '00 depending',
 '00 did',
 '00 didn',
 '00 dinner',
 '00 do',
 '00 dollar',
 '00 dollars',
 '00 don',
 '00 down',
 '00 drink',
 '00 drinks',
 '00 dumplings',
 '00 during',
 '00 each',
 '00 eggs',
 '00 entree',
 '00 entrees',
 '00 especially',
 '00 even',
 '00 every',
 '00 everything',
 '00 excluding',
 '00 expect',
 '00 expected',
 '00 extra',
 '00 fee',
 '00 felt',
 '00 finally',
 '00 fine',
 '00 first',
 '00 fish',
 '00 flour',
 '00 food',
 '00 for',
 '00 fries',
 '00 from',
 '00 generous',
 '00 get',
 '00 gets',
 '00 gift',
 '00 give',
 '00 given',
 '00 glass',
 '00 go',
 '00 good',
 '00 got',
 '00 great',
 '00 grilled',
 '00 guess',
 '00 had',
 '00 hamburger',
 '00 happy',
 '00 have',
 '00 he',
 '00 head',
 '00 here',
 '00 hoping',
 '00 hot',
 '00 hour',
 '00 how',
 '00 however',
 '00 if',
 '00 in',
 '00 including',
 '00 instead',
 '00 is',
 '00 ish',
 '00 it',
 '00 its',
 '00 just',
 '00 kind',
 '00 know',
 '00 large',
 '00 last',
 '00 later',
 '00 left',
 '00 less',
 '00 let',
 '00 like',
 '00 little',
 '00 ll',
 '00 lobster',
 '00 love',
 '00 lunch',
 '00 makes',
 '00 margarita',
 '00 may',
 '00 meal',
 '00 mean',
 '00 menu',
 '00 mimosas',
 '00 mind',
 '00 minimum',
 '00 monday',
 '00 more',
 '00 most',
 '00 music',
 '00 mussels',
 '00 must',
 '00 my',
 '00 need',
 '00 never',
 '00 nice',
 '00 no',
 '00 noon',
 '00 not',
 '00 nothing',
 '00 now',
 '00 of',
 '00 off',
 '00 oh',
 '00 okay',
 '00 on',
 '00 once',
 '00 one',
 '00 only',
 '00 opening',
 '00 or',
 '00 ordered',
 '00 otherwise',
 '00 our',
 '00 out',
 '00 over',
 '00 overall',
 '00 oyster',
 '00 oysters',
 '00 per',
 '00 person',
 '00 piece',
 '00 pieces',
 '00 pint',
 '00 pizza',
 '00 place',
 '00 plain',
 '00 plate',
 '00 please',
 '00 plus',
 '00 pm',
 '00 pop',
 '00 pork',
 '00 pound',
 '00 pp',
 '00 pretty',
 '00 price',
 '00 put',
 '00 range',
 '00 rather',
 '00 really',
 '00 reservation',
 '00 reservations',
 '00 rice',
 '00 ridiculous',
 '00 roll',
 '00 rolled',
 '00 rolls',
 '00 said',
 '00 salad',
 '00 salads',
 '00 sandwich',
 '00 sandwiches',
 '00 saturday',
 '00 seating',
 '00 seriously',
 '00 served',
 '00 service',
 '00 sesame',
 '00 sharp',
 '00 she',
 '00 shot',
 '00 should',
 '00 show',
 '00 shrimp',
 '00 side',
 '00 since',
 '00 slice',
 '00 slices',
 '00 small',
 '00 so',
 '00 soda',
 '00 solid',
 '00 sorry',
 '00 special',
 '00 spicy',
 '00 stars',
 '00 steak',
 '00 steal',
 '00 still',
 '00 sunday',
 '00 surcharge',
 '00 sure',
 '00 sweet',
 '00 tab',
 '00 taco',
 '00 tacos',
 '00 talk',
 '00 tax',
 '00 thank',
 '00 that',
 '00 the',
 '00 their',
 '00 then',
 '00 there',
 '00 these',
 '00 they',
 '00 think',
 '00 this',
 '00 though',
 '00 thought',
 '00 three',
 '00 time',
 '00 tip',
 '00 to',
 '00 today',
 '00 too',
 '00 took',
 '00 topped',
 '00 toppings',
 '00 total',
 '00 tried',
 '00 two',
 '00 unfortunately',
 '00 up',
 '00 value',
 '00 ve',
 '00 very',
 '00 waited',
 '00 want',
 '00 was',
 '00 wasn',
 '00 way',
 '00 we',
 '00 well',
 '00 went',
 '00 were',
 '00 what',
 '00 when',
 '00 which',
 '00 while',
 '00 who',
 '00 will',
 '00 wine',
 '00 wines',
 '00 wish',
 '00 with',
 '00 without',
 '00 worth',
 '00 would',
 '00 wow',
 '00 yes',
 '00 yet',
 '00 you',
 '000 00',
 '000 000',
 '000 and',
 '000 bars',
 '000 bottles',
 '000 calorie',
 '000 calories',
 '000 different',
 '000 for',
 '000 in',
 '000 layer',
 '000 layers',
 '000 leagues',
 '000 miles',
 '000 of',
 '000 other',
 '000 people',
 '000 places',
 '000 plus',
 '000 point',
 '000 restaurants',
 '000 reviews',
 '000 sq',
 '000 square',
 '000 stars',
 '000 the',
 '000 they',
 '000 times',
 '000 to',
 '000 words',
 '000 worth',
 '000 year',
 '000 years',
 '000 yelp',
 '000x better',
 '007 roll',
 '00am 00pm',
 '00am after',
 '00am and',
 '00am for',
 '00am it',
 '00am on',
 '00am or',
 '00am the',
 '00am to',
 '00am we',
 '00am when',
 '00am with',
 '00pm 00pm',
 '00pm 30pm',
 '00pm after',
 '00pm and',
 '00pm as',
 '00pm at',
 '00pm but',
 '00pm came',
 '00pm dinner',
 '00pm every',
 '00pm except',
 '00pm for',
 '00pm from',
 '00pm however',
 '00pm if',
 '00pm in',
 '00pm it',
 '00pm my',
 '00pm no',
 '00pm not',
 '00pm on',
 '00pm or',
 '00pm reservation',
 '00pm saturday',
 '00pm seating',
 '00pm since',
 '00pm so',
 '00pm that',
 '00pm the',
 '00pm there',
 '00pm they',
 '00pm this',
 '00pm to',
 '00pm was',
 '00pm we',
 '00pm when',
 '00pm which',
 '00pm with',
 '00pm you',
 '01 03',
 '01 07',
 '01 08',
 '01 10',
 '01 2014',
 '01 26',
 '01 and',
 '01 pm',
 '01 we',
 '01pm and',
 '02 15',
 '02 2013',
 '02 2014',
 '02 23',
 '02 and',
 '02 the',
 '03 05',
 '03 11',
 '03 14',
 '03 2012',
 '03 and',
 '03 pm',
 '03 when',
 '04 10',
 '04 16',
 '04 25',
 '04 26',
 '04 and',
 '04 pm',
 '05 10',
 '05 12',
 '05 and',
 '05 but',
 '05 for',
 '05 on',
 '05 pm',
 '05 that',
 '05 the',
 '05 then',
 '05 we',
 '05 which',
 '05 with',
 '05am and',
 '05pm and',
 '06 08',
 '06 09',
 '06 10',
 '06 11',
 '06 14',
 '06 2011',
 '06 2013',
 '06 2014',
 '06 22',
 '06 and',
 '06 for',
 '06 pm',
 '07 06',
 '07 11',
 '07 and',
 '07 for',
 '07 gift',
 '07 it',
 '07 my',
 '07 pm',
 '07 so',
 '07 ve',
 '07 we',
 '07 when',
 '07pm on',
 '08 02',
 '08 09',
 '08 12',
 '08 13',
 '08 31',
 '08 and',
 '08 have',
 '08 it',
 '08 my',
 '08 so',
 '08 the',
 '08 they',
 '08 this',
 '08 update',
 '08 was',
 '08 we',
 '08 went',
 '08 with',
 '09 01',
 '09 03',
 '09 05',
 '09 12',
 '09 13',
 '09 14',
 '09 17',
 '09 after',
 '09 am',
 '09 and',
 '09 but',
 '09 for',
 '09 on',
 '09 the',
 '09 this',
 '09 to',
 '09 ve',
 '09 was',
 '09 we',
 '09 with',
 '10 00',
 '10 000',
 '10 00am',
 '10 00pm',
 '10 01',
 '10 02',
 '10 03',
 '10 05',
 '10 06',
 '10 07',
 '10 08',
 '10 09',
 '10 10',
 '10 10am',
 '10 10pm',
 '10 11',
 '10 11am',
 '10 11pm',
 '10 12',
 '10 12ish',
 '10 12oz',
 '10 13',
 '10 14',
 '10 15',
 '10 15am',
 '10 15ish',
 '10 15min',
 '10 15mins',
 '10 15pm',
 '10 16',
 '10 17',
 '10 18',
 '10 19',
 '10 20',
 '10 2008',
 '10 2011',
 '10 2012',
 '10 2013',
 '10 2014',
 '10 20pm',
 '10 21',
 '10 22',
 '10 23',
 '10 24',
 '10 25',
 '10 26',
 '10 27',
 '10 28',
 '10 29',
 '10 30',
 '10 30a',
 '10 30am',
 '10 30ish',
 '10 30p',
 '10 30pm',
 '10 31',
 '10 35',
 '10 40',
 '10 40am',
 '10 40pm',
 '10 45',
 '10 45am',
 '10 45pm',
 '10 48',
 '10 49',
 '10 4pm',
 '10 50',
 '10 50am',
 '10 50pm',
 '10 55',
 '10 55am',
 '10 55pm',
 '10 58',
 '10 59',
 '10 70',
 '10 75',
 '10 79',
 '10 80',
 '10 85',
 '10 90',
 '10 95',
 '10 99',
 '10 about',
 '10 absolutely',
 '10 abv',
 '10 across',
 '10 actual',
 '10 adults',
 '10 after',
 '10 again',
 '10 alcohol',
 '10 all',
 '10 almost',
 '10 along',
 '10 also',
 '10 although',
 '10 always',
 '10 am',
 '10 amazing',
 '10 amuse',
 '10 an',
 '10 and',
 '10 another',
 '10 anyone',
 '10 apiece',
 '10 app',
 '10 appetizer',
 '10 appetizers',
 '10 apple',
 '10 apps',
 '10 are',
 '10 around',
 '10 arrived',
 '10 arts',
 '10 as',
 '10 asked',
 '10 at',
 '10 atmosphere',
 '10 available',
 '10 ave',
 '10 awesome',
 '10 back',
 '10 bags',
 '10 banh',
 '10 bar',
 '10 barstools',
 '10 bartender',
 '10 based',
 '10 basically',
 '10 bbq',
 '10 be',
 '10 beautiful',
 '10 because',
 '10 beef',
 '10 beer',
 '10 beers',
 '10 before',
 '10 being',
 '10 believe',
 '10 best',
 '10 better',
 '10 big',
 '10 bill',
 '10 bills',
 '10 birthday',
 '10 bit',
 '10 bites',
 '10 block',
 '10 blocks',
 '10 bloody',
 '10 boiled',
 '10 booths',
 '10 both',
 '10 bottle',
 '10 bottles',
 '10 bottom',
 '10 bowl',
 '10 bowls',
 '10 boxes',
 '10 braised',
 '10 bread',
 '10 breakfast',
 '10 brunch',
 '10 brussel',
 '10 buck',
 '10 bucks',
 '10 buffet',
 '10 burger',
 '10 burgers',
 '10 burrito',
 '10 but',
 '10 bux',
 '10 by',
 '10 cab',
 '10 caesar',
 '10 cake',
 '10 called',
 '10 came',
 '10 can',
 '10 cane',
 '10 cant',
 '10 carafe',
 '10 card',
 '10 cars',
 '10 cash',
 '10 cc',
 '10 celebrating',
 '10 cent',
 '10 cents',
 '10 cha',
 '10 chairs',
 '10 champagne',
 '10 charge',
 '10 cheaper',
 '10 check',
 '10 cheese',
 '10 cheesesteak',
 '10 chicken',
 '10 chili',
 '10 chips',
 '10 chive',
 '10 chives',
 '10 choices',
 '10 clams',
 '10 clock',
 '10 close',
 '10 co',
 '10 cocktail',
 '10 cocktails',
 '10 coffee',
 '10 cold',
 '10 combo',
 '10 come',
 '10 comes',
 '10 comfortably',
 '10 commandments',
 '10 cons',
 '10 considering',
 '10 cool',
 '10 cork',
 '10 corkage',
 '10 corking',
 '10 could',
 '10 couldn',
 '10 counter',
 '10 couples',
 '10 coupon',
 '10 coupons',
 '10 course',
 '10 courses',
 '10 cover',
 '10 credit',
 '10 crispy',
 '10 crostini',
 '10 cups',
 '10 curry',
 '10 customers',
 '10 daily',
 '10 day',
 '10 days',
 '10 deal',
 '10 decent',
 '10 decided',
 '10 decor',
 '10 deep',
 '10 definitely',
 '10 degree',
 '10 degrees',
 '10 delicious',
 '10 delivery',
 '10 depending',
 '10 despite',
 '10 dessert',
 '10 desserts',
 '10 devoe',
 '10 did',
 '10 didn',
 '10 different',
 '10 dining',
 '10 dinner',
 '10 discount',
 '10 dish',
 '10 dishes',
 '10 do',
 '10 doesn',
 '10 dollar',
 '10 dollars',
 '10 domestic',
 '10 don',
 '10 down',
 '10 downing',
 '10 drink',
 '10 drinks',
 '10 dry',
 '10 duck',
 '10 dumplings',
 '10 during',
 '10 ea',
 '10 each',
 '10 easily',
 '10 easy',
 '10 eat',
 '10 egg',
 '10 eggs',
 '10 empanadas',
 '10 empty',
 '10 enjoyed',
 '10 entree',
 '10 entrees',
 '10 especially',
 '10 even',
 '10 every',
 '10 everyone',
 '10 everything',
 '10 exactly',
 '10 excellent',
 '10 except',
 '10 exotic',
 '10 expect',
 '10 expected',
 '10 experience',
 '10 extra',
 '10 family',
 '10 famous',
 '10 fantastic',
 '10 fast',
 '10 favorite',
 '10 fee',
 '10 feel',
 '10 feet',
 '10 felt',
 '10 finally',
 '10 fine',
 '10 fingers',
 '10 first',
 '10 fish',
 '10 flavors',
 '10 flight',
 '10 flights',
 '10 fold',
 '10 folks',
 '10 food',
 '10 foot',
 '10 for',
 '10 free',
 '10 french',
 '10 fresh',
 '10 fried',
 '10 friendly',
 '10 friends',
 '10 fries',
 '10 from',
 '10 ft',
 '10 full',
 '10 gallon',
 '10 get',
 '10 gets',
 '10 gift',
 '10 girls',
 '10 give',
 '10 given',
 '10 glass',
 '10 glasses',
 '10 gnocchi',
 '10 go',
 '10 good',
 '10 got',
 '10 great',
 '10 greek',
 '10 grilled',
 '10 groups',
 '10 guacamole',
 '10 guess',
 '10 guests',
 '10 had',
 '10 half',
 '10 happy',
 '10 hard',
 '10 have',
 '10 haven',
 '10 he',
 '10 heads',
 '10 here',
 '10 higher',
 '10 highly',
 '10 hope',
 '10 hot',
 '10 hour',
 '10 hours',
 '10 house',
 '10 how',
 '10 however',
 '10 huge',
 '10 hungry',
 '10 if',
 '10 in',
 '10 inch',
 '10 inches',
 '10 including',
 '10 individual',
 '10 instead',
 '10 ippudo',
 '10 is',
 '10 ish',
 '10 isn',
 '10 it',
 '10 italian',
 '10 items',
 '10 its',
 '10 just',
 '10 kids',
 '10 kimchi',
 '10 kinds',
 '10 know',
 '10 ladies',
 '10 lamb',
 '10 large',
 '10 last',
 '10 lastly',
 '10 late',
 '10 later',
 '10 layer',
 '10 lb',
 '10 lbs',
 '10 left',
 '10 less',
 '10 let',
 '10 light',
 '10 like',
 '10 liked',
 '10 limit',
 '10 list',
 '10 lists',
 '10 little',
 '10 ll',
 '10 lol',
 '10 long',
 '10 lots',
 '10 love',
 '10 loved',
 '10 lunch',
 '10 lunches',
 '10 mac',
 '10 made',
 '10 main',
 '10 make',
 '10 making',
 '10 margarita',
 '10 margaritas',
 '10 mark',
 '10 max',
 '10 may',
 '10 maybe',
 '10 me',
 '10 meal',
 '10 meals',
 '10 mean',
 '10 meat',
 '10 menu',
 '10 midnight',
 '10 mile',
 '10 miles',
 '10 milkshakes',
 '10 million',
 '10 mimosas',
 '10 min',
 '10 minimum',
 '10 mins',
 '10 mintues',
 '10 minuets',
 '10 minute',
 '10 minutes',
 '10 mistake',
 '10 mns',
 '10 monday',
 '10 month',
 '10 months',
 '10 more',
 '10 most',
 '10 music',
 '10 mussels',
 '10 must',
 '10 my',
 '10 napkins',
 '10 never',
 '10 new',
 '10 next',
 '10 nice',
 '10 no',
 '10 noodle',
 '10 noodles',
 '10 nor',
 '10 not',
 '10 note',
 '10 nothing',
 '10 now',
 '10 nyc',
 '10 occasions',
 '10 of',
 ...]

**Model 1.2: Using Logistic Regression**

In [55]:
# preprocessing of text data

t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 1), min_df = 3, stop_words = 'english')
Xs1 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs1.shape)

0:01:24.494791
(608458, 66410)

In [57]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(n_jobs = -1)
score = cross_val_score(logreg, Xs1, y, cv = 2, n_jobs = -1)

print(datetime.now() - t1)
print(score)

0:06:49.827909
[0.85830457 0.85970391]

**Model 1.3: Using RandomForestClassifier**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 200, random_state = 35)
score = cross_val_score(rfc, Xs1, y, cv = 2, n_jobs = -1)

print(datetime.now() - t1)
print(score)

**Model 1.4: Using xgboost**

In [59]:

xgb_classifier = xgb.XGBClassifier()
score = cross_val_score(xgb_classifier, Xs1, y, cv = 2, n_jobs = -1)
print('Cross Validation Score: {:0.3} ± {:0.3}'.format(score.mean().round(3), score.std().round(3)))

print(datetime.now() - t1)
print(score)

0:14:07.851004
[0.86780068 0.86781296]

In [ ]:
# split data into training and testing datasets

Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, y, test_size = 0.3)

In [ ]:
xgb_classifier.fit(Xs_train, ys_train)
ys_pred = xgb_classifier.predict(Xs_test)

print('xgb acc_test score: ' accuracy_score(ys_test, ys_pred))

In [ ]:
# Plot confusion matrix

confusion_mat = pd.crosstab(ys_test, ys_pred,
                            rownames=['Actual'],
                            colnames=['Predicted'],margins=True)
confusion_mat

In [ ]:
# Print classification report

print(classification_report(ys_test, ys_pred))

In [ ]:
# Plotting ROC curve for high salary (label 1)

fpr, tpr, thresholds = roc_curve(y_test22, y_pred22)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=[8,8])
plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % roc_auc, linewidth=4)
plt.plot([0, 1], [0, 1], 'k--', linewidth=4)
plt.xlim([-0.05, 1.0])
plt.ylim([-0.05, 1.05])
plt.xlabel('False Positive Rate', fontsize=18)
plt.ylabel('True Positive Rate', fontsize=18)
plt.title('ROC for high salary', fontsize=18)
plt.legend(loc="lower right")
plt.show()

**Model 1.5: Using CNN**

## Try balancing dataset

Write a function to run pipeline of using a variety of sampling techniques

In [18]:
# preprocessing of text data

t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 1), min_df = 3, stop_words = 'english')
Xs1 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs1.shape)

0:02:35.543079
(608458, 66410)

In [ ]:
t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 1), min_df = 3)
Xs2 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs2.shape)

In [ ]:
t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 2), min_df = 3)
Xs3 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs3.shape)

In [ ]:
def run_pipeline(X, y):

    from imblearn.under_sampling import RandomUnderSampler
    from imblearn.over_sampling import RandomOverSampler, ADASYN, SMOTE
    from sklearn.ensemble import RandomForestClassifier
    
    def RandomForest(X,y):
        rfc = RandomForestClassifier(n_estimators = 200, random_state = 35)
        print(cross_val_score(rfc, X, y, cv = 2, n_jobs = -1))
        
    def xgb(X,y):
        xgb_classifier = xgb.XGBClassifier()
        print(cross_val_score(xgb_classifier, X, y, cv = 2, n_jobs = -1))
    
    def LogisticRegression(X,y):
        logreg = LogisticRegression(n_jobs = -1)
        print(cross_val_score(logreg, X, y, cv = 2, n_jobs = -1))
    
    # Undersampling and oversampling to solve for class imbalance
    model_undersample = RandomUnderSampler(random_state=42)
    X_undersample, y_undersample = model_undersample.fit_resample(Xs1, y)
    print('Undersampling:', X_undersample.shape, y_undersample.shape)
    RandomForest(X_undersample, y_undersample)
    xgb(X_undersample, y_undersample)
    LogisticRegression(X_undersample, y_undersample)
    print('\n')

    model_oversample = RandomOverSampler(random_state=42)
    X_oversample, y_oversample = model_oversample.fit_resample(Xs1, y)
    print('Oversampling:', X_oversample.shape, y_oversample.shape)
    RandomForest(X_oversample, y_oversample)
    xgb(X_oversample, y_oversample)
    LogisticRegression(X_oversample, y_oversample)
    print('\n')    

    model_ADASYN = ADASYN(random_state=42)
    X_ADASYN, y_ADASYN = model_ADASYN.fit_resample(Xs1,y)
    print('Oversampling ADASYN:', X_ADASYN.shape, y_ADASYN.shape)
    RandomForest(X_ADASYN, y_ADASYN)
    xgb(X_ADASYN, y_ADASYN)
    LogisticRegression(X_ADASYN, y_ADASYN)
    print('\n')    

    model_SMOTE = SMOTE(random_state=42)
    X_smote, y_smote = model_SMOTE.fit_resample(Xs1,y)
    print('Oversampling SMOTE:', X_smote.shape, y_smote.shape)
    RandomForest(X_smote, y_smote)
    xgb(X_smote, y_smote)
    LogisticRegression(X_smote, y_smote)
    print('\n')

In [ ]:
run_pipeline(Xs2, y)

In [ ]:
xgb_classifier = xgb.XGBClassifier()
score = cross_val_score(xgb_classifier, X_undersample, y_undersample, cv = 2, n_jobs = -1)


print(datetime.now() - t1)
print('Cross Validation Score: {:0.3} ± {:0.3}'.format(score.mean().round(3), score.std().round(3)))

## In case if want to use restaurant or user id mapping

In [7]:
# # Link reviews with restaurant name

# a = pd.merge(reviews, productIdMapping, how = 'left', left_on = ['prod_id'], right_on = ['prod_id'])

In [4]:
productIdMapping = pd.read_csv("productIdMapping", sep = '\t', names = ['Restaurant', 'prod_id'])

In [5]:
productIdMapping.shape

(5044, 2)

In [6]:
productIdMapping

                            Restaurant  prod_id
0                                Toast        0
1        Big Apple Lounge & Restaurant        1
2                           La Carreta        2
3                          Just Subs 6     2780
4      Formosa Asian Fusion Restaurant        4
5                        Dona Mercedes        5
6                Subworks Pizza & Subs        6
7                        Nai Tapas Bar        7
8                          Selva Verde        8
9                        Geno’s Steaks        9
10                        Jasmine Rice     3889
11    Tropical Breeze Jamaican Kitchen       10
12                   Piccolo Trattoria       12
13                   The Old Canal Inn     4201
14         Cedar Point Bar and Kitchen       15
15              Kelliann’s Bar & Grill       16
16            Jordan’s Hot Dog’s & Mac       17
17                          Casa Adela       18
18                  Royal Bagel & Deli       19
19                         Ocean Prime     1662
20    La Familia Ristorante & Pizzeria       22
21                           Down Town       23
22           Popeye Chicken & Biscuits       25
23                    Denapoli’s Pizza     1664
24                         John’s Deli     4270
25              La Caravana Restaurant       27
26                               Tom’s       28
27                             Munchys       29
28                  El Cubanito’s Cafe     4401
29                               Knock     2857
...                                ...      ...
5014                  Blue Point Grill     5016
5015                          Bistango     1431
5016          Buon Appetito Food Truck     2411
5017       El Rancho Grande Restaurant     1244
5018                       Dannys Deli     4917
5019                     Shyrl’s Diner     3487
5020                        City Pizza     4443
5021                             Dover     5022
5022   The Fan Sports Bar & Restaurant     4933
5023             Pizza Chef of Quechee     5024
5024                      Room Service     5025
5025                  Dish Bar & Grill     5026
5026                              Fare     4260
5027                     NIXS Hartford     3332
5028                   Iron Chef House     5028
5029                          Donostia     5029
5030                      Lucky Garden     4795
5031                          Rex 1516     5030
5032        Izumi Japanese Steak House      266
5033                      Andy’s Pizza     4009
5034                   AJ Pizza & More     4980
5035                   Pho Thanh Huong     5034
5036                           Halcyon     3334
5037                     Le Petit Cafe     2984
5038              Royal Buffet & Grill     4199
5039            Dunns River Restaurant     1277
5040            Italian Peoples Bakery     5038
5041                           Bijan’s     5041
5042               Ramayana Restaurant     5042
5043                     Best Subs the     5039

[5044 rows x 2 columns]

In [31]:
userIdMapping = pd.read_csv("userIdMapping", sep = '\t', names = ['person_id', 'user_id'])

In [32]:
userIdMapping

                     person_id  user_id
0       L4ANPtyHW1eQeXxq3Tkm1w   154347
1       FzbqZaNONgR-b5iHpoGp8Q   185064
2       F1n8h7MtVHPxgY4U1iQ-bQ   205085
3       sd00TiP5ENkm6rKYPn3p3A    38645
4       9-QHBM5i9--nUYrrj9DXXA   133524
5       FBjIChlJ437HqVe134bCVw    41313
6       2fVXWuQ7jtr8STZ6UWhPYQ   136755
7       m6i7NOocr7YlFg1CXhRV6Q   221370
8       aGWsrc0EUIz_DCGodUT-pg   100884
9       SumMCQ8oBNhZCp_X46EnWA    66978
10      Hy54GI7Sy7-7VnZk-cWXig   258271
11      SYn0dE4hsOlfruf-EJ_Q-w    15998
12      MgbcxwXzc-_4ioIGvd7P2w    61422
13      lUUTDlzQRg2tuIR78AoBVg    73495
14      2AXlmJSw97nv2Hin1Vwrsw    73970
15      K40fWNHl43QL9TersMrL5Q    29566
16      2aPI5DRNCN6jK_cv-_jAmg   118877
17      _Knfua7TBxubR9qsD7b-YA    94822
18      Nn-Pfm7lAOFvS4SzXisDug    74589
19      7Mg60yyt5o7xSGOe9NDzdg   209568
20      rR9HIaFZGaEP5L5zMoDqUA    17078
21      JgQZ0g6G4zyg07jpITubJQ    12274
22      mfgm3Nl5p-D-fUpBiY8zFQ    60579
23      ILEnjldnXlVzwEdfVvnULQ    80671
24      xBT1dhAJENYREaMt58vTyA   243370
25      cJXSY8lO5M9Xhi8Ke_tR6Q   167288
26      PAEhli30r-QvceQ5xTAsWA    82833
27      dNrdIOXRZkehQqPHrN7hPw   133639
28      d2gdJ45XJo-zsXM8PQhX3A    19592
29      jtHD55H1Ug_tuyV8t6WgWw   139418
...                        ...      ...
260247  VwCrFjF-j3ndGrsK1GB7Fw    12951
260248  sbmrijcCvqRFTM8NOvHWKw   102594
260249  FImYVr7nIwNCNiK0KV2dkw   167685
260250  jp2J7r6lcG3owU9c2OzXbQ    16771
260251  kTbb6itfWHOQxLSn5-tjvQ   112309
260252  rG303qplQvScCVW5Gfpy8g   255004
260253  GU3c_tCFSxmJolgMFrfBrw     7061
260254  rLy2QyPnM7AnTtT79owCyA   132509
260255  wudrHVAJ6qDZCHqxin0b9w   219954
260256  uV8dT3MRs0CyG3nRtYAawA   172329
260257  6FicELil_6nQ24vdd62YjA   127645
260258  AXKdSTpgvJbytE249KZNXg   117795
260259  0SmqO9zYzqbsDry0nK02Gw   238938
260260  dmYgas-hhKhnRO8Valfbow   116629
260261  lFRw_lSNkAVm88ZVuHRzwg   184470
260262  KdQU4fnObk8S56g-PEGOoQ   131269
260263  7ZUhCAOfc8sc_M9LsYLoFw    81632
260264  bRh4JM8pXNf1j05yW8PsTg    87090
260265  ToD6vulbTSXWaGpcYjeSCw    37500
260266  ljR-P7sqpyuODNJspxRXlA   174716
260267  QiX9qh1wiHtWrWXw7PHuAg   124983
260268  zYBnYTFFZaCX7wL2CUHdlQ   113933
260269  QdCtcHOYgjmY8pWyTz1E_w   144916
260270  AEz3n9xONSKVKH4p0NYSbw    42340
260271  u7Eg8cEcN0CL9UAwoEFAkA    54538
260272  jXdocchiXPP4fplMvymwXA    14168
260273  h7n-BcWQ3LgzJj5mLf1zXA   217870
260274  4axCZEnTa_swkrAd9oCCsA   166410
260275  jSFqzTlwsjnW6iI7v5GkyQ    49866
260276  GeuJUGE3s65g_gRMs_v1ig   244128

[260277 rows x 2 columns]

In [34]:
reviewGraph = pd.read_csv("reviewGraph",names=["user_id","name","rating1"], sep = '\t')

In [35]:
reviewGraph

        user_id  name  rating1
0          5044     0      1.0
1          5045     0      1.0
2          5046     0      3.0
3          5047     0      5.0
4          5048     0      5.0
5          5049     0      5.0
6          5050     0      5.0
7          5051     0      1.0
8          5052     0      2.0
9          5053     0      4.0
10         5054     0      3.0
11         5055     0      5.0
12         5056     0      5.0
13         5057     0      2.0
14         5058     0      5.0
15         5059     0      5.0
16         5060     0      5.0
17         5061     0      4.0
18         5062     0      5.0
19         5063     0      2.0
20         5064     0      2.0
21         5065     0      5.0
22         5066     0      2.0
23         5067     0      5.0
24         5068     0      4.0
25         5069     0      4.0
26         5070     0      4.0
27         5071     0      1.0
28         5072     0      4.0
29         5073     0      5.0
...         ...   ...      ...
608568    12689  5041      4.0
608569    24125  5041      5.0
608570    59981  5041      5.0
608571   195268  5041      5.0
608572    38817  5041      4.0
608573    27528  5041      5.0
608574     9501  5041      5.0
608575   153736  5041      5.0
608576   265314  5041      5.0
608577   265315  5041      5.0
608578   142624  5041      4.0
608579    17390  5041      5.0
608580    20973  5041      5.0
608581   132584  5041      5.0
608582   218220  5041      5.0
608583   265316  5042      5.0
608584   265317  5042      5.0
608585    34842  5042      5.0
608586   247830  5039      3.0
608587   265318  5039      4.0
608588   100625  5039      4.0
608589   265319  5039      5.0
608590   138941  5039      4.0
608591   166004  5039      1.0
608592    56267  5039      4.0
608593   119664  5039      4.0
608594    56277  5039      2.0
608595   265320  5039      1.0
608596   161722  5039      4.0
608597    78454  5039      4.0

[608598 rows x 3 columns]

In [37]:
reviewGraph.shape

(608598, 3)

In [38]:
reviewGraph['user_id'].value_counts()

8367      197
9501      185
7871      178
8225      159
10934     155
8351      142
7781      142
7777      136
8467      135
8011      133
8337      132
9105      132
19044     131
18780     127
13937     126
12874     123
14510     121
25871     118
14255     116
5095      112
5558      111
7688      110
9679      109
17116     109
11146     108
5620      107
8748      106
21344     106
19166     105
9755      105
         ...
29999       1
21803       1
19752       1
55792       1
11556       1
220490      1
224588      1
136547      1
247129      1
138594      1
132449      1
134496      1
259423      1
261470      1
255325      1
257372      1
251227      1
253274      1
243031      1
222541      1
245078      1
238933      1
240980      1
234835      1
236882      1
230737      1
232784      1
226639      1
228686      1
6147        1
Name: user_id, Length: 260277, dtype: int64

In [39]:
reviewGraph['name'].value_counts()

3745    7378
4698    6632
3237    4716
3136    3938
1881    3143
3875    3122
2605    2999
3876    2959
828     2943
4223    2858
56      2696
127     2677
1941    2560
3318    2536
9       2497
4083    2292
1814    2183
2127    2165
1859    2158
496     2075
3215    2072
1401    1973
1341    1958
1597    1911
2223    1870
3618    1834
1298    1780
3582    1689
4034    1680
2265    1675
        ...
2750       1
1414       1
1057       1
3243       1
1783       1
3428       1
2806       1
1707       1
392        1
1640       1
2595       1
3831       1
2536       1
1167       1
3726       1
683        1
3377       1
4641       1
2665       1
2295       1
3431       1
1168       1
3998       1
871        1
245        1
2292       1
4485       1
3942       1
2921       1
2943       1
Name: name, Length: 5044, dtype: int64