In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import roc_curve, auc, confusion_matrix, classification_report, accuracy_score

from datetime import datetime
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.linear_model import LogisticRegression

Join both review and metadata datasets from zip file

In [2]:
reviewContent = pd.read_csv("ReviewContent", names = ['user_id', 'prod_id', 'date', 'review'], sep = '\t', parse_dates = ['date'])
metadata = pd.read_csv("metadata",names=["user_id", "prod_id", "rating", "label", "date"], sep = '\t', parse_dates = ['date'])



reviews = pd.merge(reviewContent, metadata, how = 'left', 
                    left_on = ['user_id', 'prod_id', 'date'], right_on = ['user_id', 'prod_id', 'date'])

In [3]:
reviews.head()

,user_id,prod_id,date,review,rating,label
0,5044,0,2014-11-16,"Drinks were bad, the hot chocolate was watered...",1.0,-1
1,5045,0,2014-09-08,This was the worst experience I've ever had a ...,1.0,-1
2,5046,0,2013-10-06,This is located on the site of the old Spruce ...,3.0,-1
3,5047,0,2014-11-30,I enjoyed coffee and breakfast twice at Toast ...,5.0,-1
4,5048,0,2014-08-28,I love Toast! The food choices are fantastic -...,5.0,-1

In [4]:
# Convert classification of fake reviews from '-1' to '0'

reviews['label'] = reviews['label'].apply(lambda x: 0 if x == -1 else x)

In [5]:
reviews['label'].value_counts()

1    528019
0     80439
Name: label, dtype: int64

In [6]:
1- np.mean(reviews['label'])

0.13220140091838717

Given the significant class imbalance where 13.2% of all reviews are fake (based on Yelp's proprietary algorithm), we will look to address this class imbalance to improve our predictions.

## Part 1: EDA to better understand what might constitute fake reviews

In [8]:
fake_reviews = reviews[reviews['label'] == 0]
fake_reviews.shape

(80439, 6)

## Part 2: Experiment with using only review text to predict rating (w/o feature engineering)

In [12]:
model1 = reviews[['review', 'label']]

In [13]:
model1.head()

                                              review  label
0  Drinks were bad, the hot chocolate was watered...      0
1  This was the worst experience I've ever had a ...      0
2  This is located on the site of the old Spruce ...      0
3  I enjoyed coffee and breakfast twice at Toast ...      0
4  I love Toast! The food choices are fantastic -...      0

In [14]:
X = reviews['review']
y = reviews['label']

We will first use cross_validation to do a high level evaluation of the effectiveness of various model types and sampling methods using the function below. 

***Modelling techniques***
- 1) RandomForestClassifier
- 2) Xgboost
- 3) LogisticRegression

***Sampling techniques***
- 1) Oversampling
- 2) ADASYN
- 3) SMOTE

*Baseline would be 50% now since we are resampling the dataset

In [10]:
from imblearn.over_sampling import RandomOverSampler, ADASYN, SMOTE

def run_pipeline(X, y):
    t1 = datetime.now()

    
    def RandomForest(X,y):
        rfc = RandomForestClassifier(n_estimators = 10, random_state = 35)
        print(cross_val_score(rfc, X, y, cv = 2, n_jobs = -1))
        
    def xgbooster(X,y):
        xgb_classifier = xgb.XGBClassifier()
        print(cross_val_score(xgb_classifier, X, y, cv = 2, n_jobs = -1))
    
    def LogReg(X,y):
        logreg = LogisticRegression()
        print(cross_val_score(logreg, X, y, cv = 2, n_jobs = -1))
    
    # Various oversampling techniques to solve for class imbalance

    model_oversample = RandomOverSampler(random_state=42)
    X_oversample, y_oversample = model_oversample.fit_resample(X, y)
    print('Oversampling:', X_oversample.shape, y_oversample.shape)
    RandomForest(X_oversample, y_oversample)
    print(datetime.now() - t1)

    xgbooster(X_oversample, y_oversample)
    print(datetime.now() - t1)

    LogReg(X_oversample, y_oversample)
    print(datetime.now() - t1)

    print('\n')    

    model_ADASYN = ADASYN(random_state=42)
    X_ADASYN, y_ADASYN = model_ADASYN.fit_resample(X,y)
    print('Oversampling ADASYN:', X_ADASYN.shape, y_ADASYN.shape)
    RandomForest(X_ADASYN, y_ADASYN)
    print(datetime.now() - t1)

    xgbooster(X_ADASYN, y_ADASYN)
    print(datetime.now() - t1)

    LogReg(X_ADASYN, y_ADASYN)
    print(datetime.now() - t1)

    print('\n')    

    model_SMOTE = SMOTE(random_state=42)
    X_smote, y_smote = model_SMOTE.fit_resample(X,y)
    print('Oversampling SMOTE:', X_smote.shape, y_smote.shape)
    RandomForest(X_smote, y_smote)
    print(datetime.now() - t1)

    xgbooster(X_smote, y_smote)
    print(datetime.now() - t1)

    LogReg(X_smote, y_smote)
    print(datetime.now() - t1)

    print('\n')

We will run the above pipeline across various NLP preprocessing techniques (TfidVectorizer and CountVectorizer) and adjusting various parameters to see which gives the best score.

**Config 1.1 - Preprocessing of text data by INCLUDING stopwords**

In [15]:
t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 1), min_df = 3, stop_words = 'english')
Xs1 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs1.shape)

0:01:06.143387
(608458, 66410)

In [ ]:
run_pipeline(Xs1, y)

Oversampling: (1056038, 66410) (1056038,)

In [ ]:
# adjusted model since SMOTE and ADASYN are performing much better than oversampling

**Config 1.2 - Preprocessing of text data by EXCLUDING stopwords**

In [14]:
# preprocessing of text data by EXCLUDING stopwords

t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 1), min_df = 3)
Xs2 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs2.shape)

0:02:18.144109
(608458, 66718)

In [ ]:
run_pipeline(Xs2, y)

**Config 1.3 - Preprocessing of text data by EXCLUDING stopwords and with a wider range of ngrams**

In [ ]:
t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (2, 3), min_df = 3)
Xs3 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs3.shape)

In [ ]:
run_pipeline(Xs3, y)

**Config 1.4 - Preprocessing of text data using TfidVectorizer by EXCLUDING stopwords and with a wider range of ngrams**

In [ ]:
t1 = datetime.now()
tvec = TfidVectorizer(ngram_range = (2, 3), min_df = 3)
Xs4 = tvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs4.shape)

In [ ]:
run_pipeline(Xs4, y)

**Config 1.5 - Preprocessing of text data by EXCLUDING stopwords with ngrams = 1 and lemmatizer**

In [ ]:
t1 = datetime.now()
cvec = CountVectorizer(ngram_range = (1, 1), min_df = 3)
Xs5 = cvec.fit_transform(X)

print(datetime.now() - t1)
print(Xs5.shape)

In [ ]:
run_pipeline(Xs5, y)

## Part 3: Experiment with an alternative model incorporating some feature engineering from part 1 (but not using the text itself) to see if the model performance can be improved

## Part 4: Optimising model and parameter tuning

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 200, random_state = 35)
score = cross_val_score(rfc, Xs1, y, cv = 2, n_jobs = -1)

print(datetime.now() - t1)
print(score)

**Model 1.4: Using xgboost**

In [16]:

xgb_classifier = xgb.XGBClassifier()
score = cross_val_score(xgb_classifier, Xs1, y, cv = 2, n_jobs = -1)
print('Cross Validation Score: {:0.3} ± {:0.3}'.format(score.mean().round(3), score.std().round(3)))

print(datetime.now() - t1)
print(score)

Cross Validation Score: 0.868 ± 0.0
7:53:50.398131
[0.86780068 0.86781296]

In [ ]:
# split data into training and testing datasets

Xs_train, Xs_test, ys_train, ys_test = train_test_split(Xs, y, test_size = 0.3)

In [ ]:
xgb_classifier.fit(Xs_train, ys_train)
ys_pred = xgb_classifier.predict(Xs_test)

print('xgb acc_test score: ' accuracy_score(ys_test, ys_pred))

In [ ]:
# Plot confusion matrix

confusion_mat = pd.crosstab(ys_test, ys_pred,
                            rownames=['Actual'],
                            colnames=['Predicted'],margins=True)
confusion_mat

In [ ]:
# Print classification report

print(classification_report(ys_test, ys_pred))

In [ ]:
# Plotting ROC curve for high salary (label 1)

fpr, tpr, thresholds = roc_curve(y_test22, y_pred22)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=[8,8])
plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % roc_auc, linewidth=4)
plt.plot([0, 1], [0, 1], 'k--', linewidth=4)
plt.xlim([-0.05, 1.0])
plt.ylim([-0.05, 1.05])
plt.xlabel('False Positive Rate', fontsize=18)
plt.ylabel('True Positive Rate', fontsize=18)
plt.title('ROC for high salary', fontsize=18)
plt.legend(loc="lower right")
plt.show()

## Try balancing dataset

Write a function to run pipeline of using a variety of sampling techniques

In [13]:
run_pipeline(Xs1, y)

Oversampling ADASYN: (1062620, 66410) (1062620,)
1:33:02.560207
[0.77781563 0.82939683]
1:40:21.711382
[0.82721796 0.81186466]
1:46:56.507636


Oversampling SMOTE: (1056038, 66410) (1056038,)
2:08:56.176967
[0.77878679 0.83081448]
2:16:06.131034
[0.82955002 0.80796867]
2:23:54.631182

In [ ]:
run_pipeline(Xs2, y)

Undersampling: (160878, 66718) (160878,)
[0.59576082 0.59602427]
0:02:48.640526
[0.64521382 0.64305428]
0:05:05.102977
[0.62255097 0.6194709 ]
0:07:25.260128


Oversampling: (1056038, 66718) (1056038,)
[0.90533503 0.91234011]
0:42:48.615760
[0.64311579 0.64750255]
0:57:07.186804
[0.66410742 0.66176532]
1:53:08.313904

In [ ]:
xgb_classifier = xgb.XGBClassifier()
score = cross_val_score(xgb_classifier, X_undersample, y_undersample, cv = 2, n_jobs = -1)


print(datetime.now() - t1)
print('Cross Validation Score: {:0.3} ± {:0.3}'.format(score.mean().round(3), score.std().round(3)))

## In case if want to use restaurant or user id mapping

In [7]:
# # Link reviews with restaurant name

# a = pd.merge(reviews, productIdMapping, how = 'left', left_on = ['prod_id'], right_on = ['prod_id'])

In [4]:
productIdMapping = pd.read_csv("productIdMapping", sep = '\t', names = ['Restaurant', 'prod_id'])

In [5]:
productIdMapping.shape

(5044, 2)

In [6]:
productIdMapping

                            Restaurant  prod_id
0                                Toast        0
1        Big Apple Lounge & Restaurant        1
2                           La Carreta        2
3                          Just Subs 6     2780
4      Formosa Asian Fusion Restaurant        4
5                        Dona Mercedes        5
6                Subworks Pizza & Subs        6
7                        Nai Tapas Bar        7
8                          Selva Verde        8
9                        Geno’s Steaks        9
10                        Jasmine Rice     3889
11    Tropical Breeze Jamaican Kitchen       10
12                   Piccolo Trattoria       12
13                   The Old Canal Inn     4201
14         Cedar Point Bar and Kitchen       15
15              Kelliann’s Bar & Grill       16
16            Jordan’s Hot Dog’s & Mac       17
17                          Casa Adela       18
18                  Royal Bagel & Deli       19
19                         Ocean Prime     1662
20    La Familia Ristorante & Pizzeria       22
21                           Down Town       23
22           Popeye Chicken & Biscuits       25
23                    Denapoli’s Pizza     1664
24                         John’s Deli     4270
25              La Caravana Restaurant       27
26                               Tom’s       28
27                             Munchys       29
28                  El Cubanito’s Cafe     4401
29                               Knock     2857
...                                ...      ...
5014                  Blue Point Grill     5016
5015                          Bistango     1431
5016          Buon Appetito Food Truck     2411
5017       El Rancho Grande Restaurant     1244
5018                       Dannys Deli     4917
5019                     Shyrl’s Diner     3487
5020                        City Pizza     4443
5021                             Dover     5022
5022   The Fan Sports Bar & Restaurant     4933
5023             Pizza Chef of Quechee     5024
5024                      Room Service     5025
5025                  Dish Bar & Grill     5026
5026                              Fare     4260
5027                     NIXS Hartford     3332
5028                   Iron Chef House     5028
5029                          Donostia     5029
5030                      Lucky Garden     4795
5031                          Rex 1516     5030
5032        Izumi Japanese Steak House      266
5033                      Andy’s Pizza     4009
5034                   AJ Pizza & More     4980
5035                   Pho Thanh Huong     5034
5036                           Halcyon     3334
5037                     Le Petit Cafe     2984
5038              Royal Buffet & Grill     4199
5039            Dunns River Restaurant     1277
5040            Italian Peoples Bakery     5038
5041                           Bijan’s     5041
5042               Ramayana Restaurant     5042
5043                     Best Subs the     5039

[5044 rows x 2 columns]

In [31]:
userIdMapping = pd.read_csv("userIdMapping", sep = '\t', names = ['person_id', 'user_id'])

In [32]:
userIdMapping

                     person_id  user_id
0       L4ANPtyHW1eQeXxq3Tkm1w   154347
1       FzbqZaNONgR-b5iHpoGp8Q   185064
2       F1n8h7MtVHPxgY4U1iQ-bQ   205085
3       sd00TiP5ENkm6rKYPn3p3A    38645
4       9-QHBM5i9--nUYrrj9DXXA   133524
5       FBjIChlJ437HqVe134bCVw    41313
6       2fVXWuQ7jtr8STZ6UWhPYQ   136755
7       m6i7NOocr7YlFg1CXhRV6Q   221370
8       aGWsrc0EUIz_DCGodUT-pg   100884
9       SumMCQ8oBNhZCp_X46EnWA    66978
10      Hy54GI7Sy7-7VnZk-cWXig   258271
11      SYn0dE4hsOlfruf-EJ_Q-w    15998
12      MgbcxwXzc-_4ioIGvd7P2w    61422
13      lUUTDlzQRg2tuIR78AoBVg    73495
14      2AXlmJSw97nv2Hin1Vwrsw    73970
15      K40fWNHl43QL9TersMrL5Q    29566
16      2aPI5DRNCN6jK_cv-_jAmg   118877
17      _Knfua7TBxubR9qsD7b-YA    94822
18      Nn-Pfm7lAOFvS4SzXisDug    74589
19      7Mg60yyt5o7xSGOe9NDzdg   209568
20      rR9HIaFZGaEP5L5zMoDqUA    17078
21      JgQZ0g6G4zyg07jpITubJQ    12274
22      mfgm3Nl5p-D-fUpBiY8zFQ    60579
23      ILEnjldnXlVzwEdfVvnULQ    80671
24      xBT1dhAJENYREaMt58vTyA   243370
25      cJXSY8lO5M9Xhi8Ke_tR6Q   167288
26      PAEhli30r-QvceQ5xTAsWA    82833
27      dNrdIOXRZkehQqPHrN7hPw   133639
28      d2gdJ45XJo-zsXM8PQhX3A    19592
29      jtHD55H1Ug_tuyV8t6WgWw   139418
...                        ...      ...
260247  VwCrFjF-j3ndGrsK1GB7Fw    12951
260248  sbmrijcCvqRFTM8NOvHWKw   102594
260249  FImYVr7nIwNCNiK0KV2dkw   167685
260250  jp2J7r6lcG3owU9c2OzXbQ    16771
260251  kTbb6itfWHOQxLSn5-tjvQ   112309
260252  rG303qplQvScCVW5Gfpy8g   255004
260253  GU3c_tCFSxmJolgMFrfBrw     7061
260254  rLy2QyPnM7AnTtT79owCyA   132509
260255  wudrHVAJ6qDZCHqxin0b9w   219954
260256  uV8dT3MRs0CyG3nRtYAawA   172329
260257  6FicELil_6nQ24vdd62YjA   127645
260258  AXKdSTpgvJbytE249KZNXg   117795
260259  0SmqO9zYzqbsDry0nK02Gw   238938
260260  dmYgas-hhKhnRO8Valfbow   116629
260261  lFRw_lSNkAVm88ZVuHRzwg   184470
260262  KdQU4fnObk8S56g-PEGOoQ   131269
260263  7ZUhCAOfc8sc_M9LsYLoFw    81632
260264  bRh4JM8pXNf1j05yW8PsTg    87090
260265  ToD6vulbTSXWaGpcYjeSCw    37500
260266  ljR-P7sqpyuODNJspxRXlA   174716
260267  QiX9qh1wiHtWrWXw7PHuAg   124983
260268  zYBnYTFFZaCX7wL2CUHdlQ   113933
260269  QdCtcHOYgjmY8pWyTz1E_w   144916
260270  AEz3n9xONSKVKH4p0NYSbw    42340
260271  u7Eg8cEcN0CL9UAwoEFAkA    54538
260272  jXdocchiXPP4fplMvymwXA    14168
260273  h7n-BcWQ3LgzJj5mLf1zXA   217870
260274  4axCZEnTa_swkrAd9oCCsA   166410
260275  jSFqzTlwsjnW6iI7v5GkyQ    49866
260276  GeuJUGE3s65g_gRMs_v1ig   244128

[260277 rows x 2 columns]

In [34]:
reviewGraph = pd.read_csv("reviewGraph",names=["user_id","name","rating1"], sep = '\t')

In [35]:
reviewGraph

        user_id  name  rating1
0          5044     0      1.0
1          5045     0      1.0
2          5046     0      3.0
3          5047     0      5.0
4          5048     0      5.0
5          5049     0      5.0
6          5050     0      5.0
7          5051     0      1.0
8          5052     0      2.0
9          5053     0      4.0
10         5054     0      3.0
11         5055     0      5.0
12         5056     0      5.0
13         5057     0      2.0
14         5058     0      5.0
15         5059     0      5.0
16         5060     0      5.0
17         5061     0      4.0
18         5062     0      5.0
19         5063     0      2.0
20         5064     0      2.0
21         5065     0      5.0
22         5066     0      2.0
23         5067     0      5.0
24         5068     0      4.0
25         5069     0      4.0
26         5070     0      4.0
27         5071     0      1.0
28         5072     0      4.0
29         5073     0      5.0
...         ...   ...      ...
608568    12689  5041      4.0
608569    24125  5041      5.0
608570    59981  5041      5.0
608571   195268  5041      5.0
608572    38817  5041      4.0
608573    27528  5041      5.0
608574     9501  5041      5.0
608575   153736  5041      5.0
608576   265314  5041      5.0
608577   265315  5041      5.0
608578   142624  5041      4.0
608579    17390  5041      5.0
608580    20973  5041      5.0
608581   132584  5041      5.0
608582   218220  5041      5.0
608583   265316  5042      5.0
608584   265317  5042      5.0
608585    34842  5042      5.0
608586   247830  5039      3.0
608587   265318  5039      4.0
608588   100625  5039      4.0
608589   265319  5039      5.0
608590   138941  5039      4.0
608591   166004  5039      1.0
608592    56267  5039      4.0
608593   119664  5039      4.0
608594    56277  5039      2.0
608595   265320  5039      1.0
608596   161722  5039      4.0
608597    78454  5039      4.0

[608598 rows x 3 columns]

In [37]:
reviewGraph.shape

(608598, 3)

In [38]:
reviewGraph['user_id'].value_counts()

8367      197
9501      185
7871      178
8225      159
10934     155
8351      142
7781      142
7777      136
8467      135
8011      133
8337      132
9105      132
19044     131
18780     127
13937     126
12874     123
14510     121
25871     118
14255     116
5095      112
5558      111
7688      110
9679      109
17116     109
11146     108
5620      107
8748      106
21344     106
19166     105
9755      105
         ...
29999       1
21803       1
19752       1
55792       1
11556       1
220490      1
224588      1
136547      1
247129      1
138594      1
132449      1
134496      1
259423      1
261470      1
255325      1
257372      1
251227      1
253274      1
243031      1
222541      1
245078      1
238933      1
240980      1
234835      1
236882      1
230737      1
232784      1
226639      1
228686      1
6147        1
Name: user_id, Length: 260277, dtype: int64

In [39]:
reviewGraph['name'].value_counts()

3745    7378
4698    6632
3237    4716
3136    3938
1881    3143
3875    3122
2605    2999
3876    2959
828     2943
4223    2858
56      2696
127     2677
1941    2560
3318    2536
9       2497
4083    2292
1814    2183
2127    2165
1859    2158
496     2075
3215    2072
1401    1973
1341    1958
1597    1911
2223    1870
3618    1834
1298    1780
3582    1689
4034    1680
2265    1675
        ...
2750       1
1414       1
1057       1
3243       1
1783       1
3428       1
2806       1
1707       1
392        1
1640       1
2595       1
3831       1
2536       1
1167       1
3726       1
683        1
3377       1
4641       1
2665       1
2295       1
3431       1
1168       1
3998       1
871        1
245        1
2292       1
4485       1
3942       1
2921       1
2943       1
Name: name, Length: 5044, dtype: int64